classdef AnalysisParameterSettings < matlab.wsdl.internal.WsdlObject
    % AnalysisParameterSettings(AnschlKnID,CalcOnlyLoadedData,ConXML,DoRecondResizing,EleID,ExcludeElementsInMaint,ExcludeElementsInstalled,ExcludeOutOfOperElements,ExcludeProjectedElements,ExclutionDateForInstalled,ExclutionDateForOutOfOper,IncludeBoundaryElementsInCalculation,ItemTypeNameForRecondResizingField,ItemlibNameForRecondResizing,ItemlibSubNameForRecondResizing,LibItemTypeNameForRecondResizing,LibNameForRecondResizing,LibSubNameForRecondResizing,ListOfRelayIDs,ListOfSelectedFeederIDs,ListOfSelectedPartNetwIDs,ListOfShortCircuitLocationIDs,LogName,MediumType,NCalc,RelayID,SelectedRecondResizElements)  AnalysisParameterSettings object for use with <a href="matlab:doc NeplanService">NeplanService</a> web client
    %
    %     AnschlKnID - string
    %     CalcOnlyLoadedData - logical or numeric scalar (XML boolean)
    %     ConXML - string
    %     DoRecondResizing - logical or numeric scalar (XML boolean)
    %     EleID - string
    %     ExcludeElementsInMaint - logical or numeric scalar (XML boolean)
    %     ExcludeElementsInstalled - logical or numeric scalar (XML boolean)
    %     ExcludeOutOfOperElements - logical or numeric scalar (XML boolean)
    %     ExcludeProjectedElements - logical or numeric scalar (XML boolean)
    %     ExclutionDateForInstalled - string
    %     ExclutionDateForOutOfOper - string
    %     IncludeBoundaryElementsInCalculation - logical or numeric scalar (XML boolean)
    %     ItemTypeNameForRecondResizingField - string
    %     ItemlibNameForRecondResizing - string
    %     ItemlibSubNameForRecondResizing - string
    %     LibItemTypeNameForRecondResizing - string
    %     LibNameForRecondResizing - string
    %     LibSubNameForRecondResizing - string
    %     ListOfRelayIDs - <a href="matlab:doc wsdl.neplanservice.ArrayOfguid">ArrayOfguid</a>
    %     ListOfSelectedFeederIDs - <a href="matlab:doc wsdl.neplanservice.ArrayOfguid">ArrayOfguid</a>
    %     ListOfSelectedPartNetwIDs - <a href="matlab:doc wsdl.neplanservice.ArrayOfguid">ArrayOfguid</a>
    %     ListOfShortCircuitLocationIDs - <a href="matlab:doc wsdl.neplanservice.ArrayOfguid">ArrayOfguid</a>
    %     LogName - string
    %     MediumType - string
    %     NCalc - numeric scalar (XML int)
    %     RelayID - string
    %     SelectedRecondResizElements - <a href="matlab:doc wsdl.neplanservice.ArrayOfguid">ArrayOfguid</a>
    %
    % To create a AnalysisParameterSettings, use <a href="matlab:doc NeplanService.getAnalysisParameterSettings">NeplanService.getAnalysisParameterSettings</a>.
    %
    %
    % See also <a href="matlab:doc NeplanService">NeplanService</a>.
    
    % This file generated by matlab.wsdl.createWSDLClient at 07-Jan-2018 16:39:55
    % from https://demo.neplan.ch/NEPLAN360_Demo/Services/External/NeplanService.svc?singleWsdl.  
    % Please do not alter this file.
    properties 
        AnschlKnID
        CalcOnlyLoadedData
        ConXML
        DoRecondResizing
        EleID
        ExcludeElementsInMaint
        ExcludeElementsInstalled
        ExcludeOutOfOperElements
        ExcludeProjectedElements
        ExclutionDateForInstalled
        ExclutionDateForOutOfOper
        IncludeBoundaryElementsInCalculation
        ItemTypeNameForRecondResizingField
        ItemlibNameForRecondResizing
        ItemlibSubNameForRecondResizing
        LibItemTypeNameForRecondResizing
        LibNameForRecondResizing
        LibSubNameForRecondResizing
        ListOfRelayIDs
        ListOfSelectedFeederIDs
        ListOfSelectedPartNetwIDs
        ListOfShortCircuitLocationIDs
        LogName
        MediumType
        NCalc
        RelayID
        SelectedRecondResizElements
    end
    
    methods
        function obj = AnalysisParameterSettings(AnschlKnID,CalcOnlyLoadedData,ConXML,DoRecondResizing,EleID,ExcludeElementsInMaint,ExcludeElementsInstalled,ExcludeOutOfOperElements,ExcludeProjectedElements,ExclutionDateForInstalled,ExclutionDateForOutOfOper,IncludeBoundaryElementsInCalculation,ItemTypeNameForRecondResizingField,ItemlibNameForRecondResizing,ItemlibSubNameForRecondResizing,LibItemTypeNameForRecondResizing,LibNameForRecondResizing,LibSubNameForRecondResizing,ListOfRelayIDs,ListOfSelectedFeederIDs,ListOfSelectedPartNetwIDs,ListOfShortCircuitLocationIDs,LogName,MediumType,NCalc,RelayID,SelectedRecondResizElements)
            if nargin == 0, return, end
            if nargin > 0
                obj.AnschlKnID = AnschlKnID;
            end
            if nargin > 1
                obj.CalcOnlyLoadedData = CalcOnlyLoadedData;
            end
            if nargin > 2
                obj.ConXML = ConXML;
            end
            if nargin > 3
                obj.DoRecondResizing = DoRecondResizing;
            end
            if nargin > 4
                obj.EleID = EleID;
            end
            if nargin > 5
                obj.ExcludeElementsInMaint = ExcludeElementsInMaint;
            end
            if nargin > 6
                obj.ExcludeElementsInstalled = ExcludeElementsInstalled;
            end
            if nargin > 7
                obj.ExcludeOutOfOperElements = ExcludeOutOfOperElements;
            end
            if nargin > 8
                obj.ExcludeProjectedElements = ExcludeProjectedElements;
            end
            if nargin > 9
                obj.ExclutionDateForInstalled = ExclutionDateForInstalled;
            end
            if nargin > 10
                obj.ExclutionDateForOutOfOper = ExclutionDateForOutOfOper;
            end
            if nargin > 11
                obj.IncludeBoundaryElementsInCalculation = IncludeBoundaryElementsInCalculation;
            end
            if nargin > 12
                obj.ItemTypeNameForRecondResizingField = ItemTypeNameForRecondResizingField;
            end
            if nargin > 13
                obj.ItemlibNameForRecondResizing = ItemlibNameForRecondResizing;
            end
            if nargin > 14
                obj.ItemlibSubNameForRecondResizing = ItemlibSubNameForRecondResizing;
            end
            if nargin > 15
                obj.LibItemTypeNameForRecondResizing = LibItemTypeNameForRecondResizing;
            end
            if nargin > 16
                obj.LibNameForRecondResizing = LibNameForRecondResizing;
            end
            if nargin > 17
                obj.LibSubNameForRecondResizing = LibSubNameForRecondResizing;
            end
            if nargin > 18
                obj.ListOfRelayIDs = ListOfRelayIDs;
            end
            if nargin > 19
                obj.ListOfSelectedFeederIDs = ListOfSelectedFeederIDs;
            end
            if nargin > 20
                obj.ListOfSelectedPartNetwIDs = ListOfSelectedPartNetwIDs;
            end
            if nargin > 21
                obj.ListOfShortCircuitLocationIDs = ListOfShortCircuitLocationIDs;
            end
            if nargin > 22
                obj.LogName = LogName;
            end
            if nargin > 23
                obj.MediumType = MediumType;
            end
            if nargin > 24
                obj.NCalc = NCalc;
            end
            if nargin > 25
                obj.RelayID = RelayID;
            end
            if nargin > 26
                obj.SelectedRecondResizElements = SelectedRecondResizElements;
            end
        end
        function obj = set.AnschlKnID(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','AnschlKnID'},value,'string',true,false);
            obj.AnschlKnID = value;
        end        

        function obj = set.CalcOnlyLoadedData(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','CalcOnlyLoadedData'},value,'boolean',true,false);
            obj.CalcOnlyLoadedData = value;
        end        

        function obj = set.ConXML(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ConXML'},value,'string',true,false);
            obj.ConXML = value;
        end        

        function obj = set.DoRecondResizing(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','DoRecondResizing'},value,'boolean',true,false);
            obj.DoRecondResizing = value;
        end        

        function obj = set.EleID(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','EleID'},value,'string',true,false);
            obj.EleID = value;
        end        

        function obj = set.ExcludeElementsInMaint(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ExcludeElementsInMaint'},value,'boolean',true,false);
            obj.ExcludeElementsInMaint = value;
        end        

        function obj = set.ExcludeElementsInstalled(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ExcludeElementsInstalled'},value,'boolean',true,false);
            obj.ExcludeElementsInstalled = value;
        end        

        function obj = set.ExcludeOutOfOperElements(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ExcludeOutOfOperElements'},value,'boolean',true,false);
            obj.ExcludeOutOfOperElements = value;
        end        

        function obj = set.ExcludeProjectedElements(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ExcludeProjectedElements'},value,'boolean',true,false);
            obj.ExcludeProjectedElements = value;
        end        

        function obj = set.ExclutionDateForInstalled(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ExclutionDateForInstalled'},value,'string',true,false);
            obj.ExclutionDateForInstalled = value;
        end        

        function obj = set.ExclutionDateForOutOfOper(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ExclutionDateForOutOfOper'},value,'string',true,false);
            obj.ExclutionDateForOutOfOper = value;
        end        

        function obj = set.IncludeBoundaryElementsInCalculation(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','IncludeBoundaryElementsInCalculation'},value,'boolean',true,false);
            obj.IncludeBoundaryElementsInCalculation = value;
        end        

        function obj = set.ItemTypeNameForRecondResizingField(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ItemTypeNameForRecondResizingField'},value,'string',true,false);
            obj.ItemTypeNameForRecondResizingField = value;
        end        

        function obj = set.ItemlibNameForRecondResizing(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ItemlibNameForRecondResizing'},value,'string',true,false);
            obj.ItemlibNameForRecondResizing = value;
        end        

        function obj = set.ItemlibSubNameForRecondResizing(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','ItemlibSubNameForRecondResizing'},value,'string',true,false);
            obj.ItemlibSubNameForRecondResizing = value;
        end        

        function obj = set.LibItemTypeNameForRecondResizing(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','LibItemTypeNameForRecondResizing'},value,'string',true,false);
            obj.LibItemTypeNameForRecondResizing = value;
        end        

        function obj = set.LibNameForRecondResizing(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','LibNameForRecondResizing'},value,'string',true,false);
            obj.LibNameForRecondResizing = value;
        end        

        function obj = set.LibSubNameForRecondResizing(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','LibSubNameForRecondResizing'},value,'string',true,false);
            obj.LibSubNameForRecondResizing = value;
        end        

        function obj = set.ListOfRelayIDs(obj, value)
            if ~isempty(value) && ~isa(value,'wsdl.neplanservice.ArrayOfguid')
                error(message('MATLAB:webservices:VarShouldBeAType','ListOfRelayIDs', 'wsdl.neplanservice.ArrayOfguid', 'ArrayOfguid'))
            end
            obj.ListOfRelayIDs = value;
        end        

        function obj = set.ListOfSelectedFeederIDs(obj, value)
            if ~isempty(value) && ~isa(value,'wsdl.neplanservice.ArrayOfguid')
                error(message('MATLAB:webservices:VarShouldBeAType','ListOfSelectedFeederIDs', 'wsdl.neplanservice.ArrayOfguid', 'ArrayOfguid'))
            end
            obj.ListOfSelectedFeederIDs = value;
        end        

        function obj = set.ListOfSelectedPartNetwIDs(obj, value)
            if ~isempty(value) && ~isa(value,'wsdl.neplanservice.ArrayOfguid')
                error(message('MATLAB:webservices:VarShouldBeAType','ListOfSelectedPartNetwIDs', 'wsdl.neplanservice.ArrayOfguid', 'ArrayOfguid'))
            end
            obj.ListOfSelectedPartNetwIDs = value;
        end        

        function obj = set.ListOfShortCircuitLocationIDs(obj, value)
            if ~isempty(value) && ~isa(value,'wsdl.neplanservice.ArrayOfguid')
                error(message('MATLAB:webservices:VarShouldBeAType','ListOfShortCircuitLocationIDs', 'wsdl.neplanservice.ArrayOfguid', 'ArrayOfguid'))
            end
            obj.ListOfShortCircuitLocationIDs = value;
        end        

        function obj = set.LogName(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','LogName'},value,'string',true,false);
            obj.LogName = value;
        end        

        function obj = set.MediumType(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','MediumType'},value,'string',true,false);
            obj.MediumType = value;
        end        

        function obj = set.NCalc(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','NCalc'},value,'int',true,false);
            obj.NCalc = value;
        end        

        function obj = set.RelayID(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisParameterSettings','RelayID'},value,'string',true,false);
            obj.RelayID = value;
        end        

        function obj = set.SelectedRecondResizElements(obj, value)
            if ~isempty(value) && ~isa(value,'wsdl.neplanservice.ArrayOfguid')
                error(message('MATLAB:webservices:VarShouldBeAType','SelectedRecondResizElements', 'wsdl.neplanservice.ArrayOfguid', 'ArrayOfguid'))
            end
            obj.SelectedRecondResizElements = value;
        end
    end

    methods (Hidden, Access = {?matlab.wsdl.internal.WsdlObject,?NeplanService,?matlab.wsdl.internal.WsdlObject,?wsdl.neplanservice.ExternalProject,?wsdl.neplanservice.ArrayOfdouble,?wsdl.neplanservice.LoadData,?wsdl.neplanservice.string,?wsdl.neplanservice.ArrayOfImportElementItem,?wsdl.neplanservice.ArrayOfLoadData,?wsdl.neplanservice.ArrayOfstring,?wsdl.neplanservice.ArrayOfNeplanServiceElementResult,?wsdl.neplanservice.AnalysisParameterSettings,?wsdl.neplanservice.AnalysisReturnInfo,?wsdl.neplanservice.ArrayOfImportFeederItem,?wsdl.neplanservice.base64Binary,?wsdl.neplanservice.ArrayOfKeyValuePairOfstringstring,?wsdl.neplanservice.ArrayOfKeyValuePairOfstringNeplanServiceConnectionInfomHiA0HHi,?wsdl.neplanservice.ArrayOfNeplanServiceLoadGenerationInfo,?wsdl.neplanservice.ArrayOfguid,?wsdl.neplanservice.NeplanDomainServiceImportReturnInfo,?wsdl.neplanservice.ImportElementItem,?wsdl.neplanservice.ArrayOfTechDataValue,?wsdl.neplanservice.WaterLoadData,?wsdl.neplanservice.ArrayOfLineSectionData,?wsdl.neplanservice.TechDataValue,?wsdl.neplanservice.ImportFeederItem,?wsdl.neplanservice.NeplanServiceElementResult,?wsdl.neplanservice.NeplanServiceLoadGenerationInfo,?wsdl.neplanservice.KeyValuePairOfstringstring,?wsdl.neplanservice.KeyValuePairOfstringNeplanServiceConnectionInfomHiA0HHi,?wsdl.neplanservice.NeplanServiceConnectionInfo,?wsdl.neplanservice.LineSectionData,?wsdl.neplanservice.ArrayOfAnalysisReturnInfoCableSizingLineData,?wsdl.neplanservice.ArrayOfAnalysisReturnInfoRelayResultData,?wsdl.neplanservice.AnalysisReturnInfoCableSizingLineData,?wsdl.neplanservice.AnalysisReturnInfoRelayResultData})
        function validate(obj)
        % Test for required fields
            arrayfun(@(x) x.checkFields({},{},{x.ListOfRelayIDs,x.ListOfSelectedFeederIDs,x.ListOfSelectedPartNetwIDs,x.ListOfShortCircuitLocationIDs,x.SelectedRecondResizElements}), obj);
        end
    end

    methods (Hidden, Access = protected)
        function jobj = getOneObj(obj)
        % Return the Java object corresponding to this object.  Intended
        % to be invoked from superclass.
            obj.validate
            import matlab.wsdl.internal.fromMATLAB
            jobj = neplanservice.AnalysisParameterSettings;  % create empty Java object
            % populate fields of object
            jobj.setAnschlKnID(fromMATLAB({'AnalysisParameterSettings','AnschlKnID'},obj.AnschlKnID,'string',true));
            jobj.setCalcOnlyLoadedData(fromMATLAB({'AnalysisParameterSettings','CalcOnlyLoadedData'},obj.CalcOnlyLoadedData,'boolean',true));
            jobj.setConXML(fromMATLAB({'AnalysisParameterSettings','ConXML'},obj.ConXML,'string',true));
            jobj.setDoRecondResizing(fromMATLAB({'AnalysisParameterSettings','DoRecondResizing'},obj.DoRecondResizing,'boolean',true));
            jobj.setEleID(fromMATLAB({'AnalysisParameterSettings','EleID'},obj.EleID,'string',true));
            jobj.setExcludeElementsInMaint(fromMATLAB({'AnalysisParameterSettings','ExcludeElementsInMaint'},obj.ExcludeElementsInMaint,'boolean',true));
            jobj.setExcludeElementsInstalled(fromMATLAB({'AnalysisParameterSettings','ExcludeElementsInstalled'},obj.ExcludeElementsInstalled,'boolean',true));
            jobj.setExcludeOutOfOperElements(fromMATLAB({'AnalysisParameterSettings','ExcludeOutOfOperElements'},obj.ExcludeOutOfOperElements,'boolean',true));
            jobj.setExcludeProjectedElements(fromMATLAB({'AnalysisParameterSettings','ExcludeProjectedElements'},obj.ExcludeProjectedElements,'boolean',true));
            jobj.setExclutionDateForInstalled(fromMATLAB({'AnalysisParameterSettings','ExclutionDateForInstalled'},obj.ExclutionDateForInstalled,'string',true));
            jobj.setExclutionDateForOutOfOper(fromMATLAB({'AnalysisParameterSettings','ExclutionDateForOutOfOper'},obj.ExclutionDateForOutOfOper,'string',true));
            jobj.setIncludeBoundaryElementsInCalculation(fromMATLAB({'AnalysisParameterSettings','IncludeBoundaryElementsInCalculation'},obj.IncludeBoundaryElementsInCalculation,'boolean',true));
            jobj.setItemTypeNameForRecondResizingField(fromMATLAB({'AnalysisParameterSettings','ItemTypeNameForRecondResizingField'},obj.ItemTypeNameForRecondResizingField,'string',true));
            jobj.setItemlibNameForRecondResizing(fromMATLAB({'AnalysisParameterSettings','ItemlibNameForRecondResizing'},obj.ItemlibNameForRecondResizing,'string',true));
            jobj.setItemlibSubNameForRecondResizing(fromMATLAB({'AnalysisParameterSettings','ItemlibSubNameForRecondResizing'},obj.ItemlibSubNameForRecondResizing,'string',true));
            jobj.setLibItemTypeNameForRecondResizing(fromMATLAB({'AnalysisParameterSettings','LibItemTypeNameForRecondResizing'},obj.LibItemTypeNameForRecondResizing,'string',true));
            jobj.setLibNameForRecondResizing(fromMATLAB({'AnalysisParameterSettings','LibNameForRecondResizing'},obj.LibNameForRecondResizing,'string',true));
            jobj.setLibSubNameForRecondResizing(fromMATLAB({'AnalysisParameterSettings','LibSubNameForRecondResizing'},obj.LibSubNameForRecondResizing,'string',true));
            if ~isempty(obj.ListOfRelayIDs)
                jobj.setListOfRelayIDs(obj.ListOfRelayIDs.getObj);
            end
            if ~isempty(obj.ListOfSelectedFeederIDs)
                jobj.setListOfSelectedFeederIDs(obj.ListOfSelectedFeederIDs.getObj);
            end
            if ~isempty(obj.ListOfSelectedPartNetwIDs)
                jobj.setListOfSelectedPartNetwIDs(obj.ListOfSelectedPartNetwIDs.getObj);
            end
            if ~isempty(obj.ListOfShortCircuitLocationIDs)
                jobj.setListOfShortCircuitLocationIDs(obj.ListOfShortCircuitLocationIDs.getObj);
            end
            jobj.setLogName(fromMATLAB({'AnalysisParameterSettings','LogName'},obj.LogName,'string',true));
            jobj.setMediumType(fromMATLAB({'AnalysisParameterSettings','MediumType'},obj.MediumType,'string',true));
            jobj.setNCalc(fromMATLAB({'AnalysisParameterSettings','NCalc'},obj.NCalc,'int',true));
            jobj.setRelayID(fromMATLAB({'AnalysisParameterSettings','RelayID'},obj.RelayID,'string',true));
            if ~isempty(obj.SelectedRecondResizElements)
                jobj.setSelectedRecondResizElements(obj.SelectedRecondResizElements.getObj);
            end
        end
    end

    methods (Static, Hidden, Access = {?NeplanService,?matlab.wsdl.internal.WsdlObject,?wsdl.neplanservice.ExternalProject,?wsdl.neplanservice.ArrayOfdouble,?wsdl.neplanservice.LoadData,?wsdl.neplanservice.string,?wsdl.neplanservice.ArrayOfImportElementItem,?wsdl.neplanservice.ArrayOfLoadData,?wsdl.neplanservice.ArrayOfstring,?wsdl.neplanservice.ArrayOfNeplanServiceElementResult,?wsdl.neplanservice.AnalysisParameterSettings,?wsdl.neplanservice.AnalysisReturnInfo,?wsdl.neplanservice.ArrayOfImportFeederItem,?wsdl.neplanservice.base64Binary,?wsdl.neplanservice.ArrayOfKeyValuePairOfstringstring,?wsdl.neplanservice.ArrayOfKeyValuePairOfstringNeplanServiceConnectionInfomHiA0HHi,?wsdl.neplanservice.ArrayOfNeplanServiceLoadGenerationInfo,?wsdl.neplanservice.ArrayOfguid,?wsdl.neplanservice.NeplanDomainServiceImportReturnInfo,?wsdl.neplanservice.ImportElementItem,?wsdl.neplanservice.ArrayOfTechDataValue,?wsdl.neplanservice.WaterLoadData,?wsdl.neplanservice.ArrayOfLineSectionData,?wsdl.neplanservice.TechDataValue,?wsdl.neplanservice.ImportFeederItem,?wsdl.neplanservice.NeplanServiceElementResult,?wsdl.neplanservice.NeplanServiceLoadGenerationInfo,?wsdl.neplanservice.KeyValuePairOfstringstring,?wsdl.neplanservice.KeyValuePairOfstringNeplanServiceConnectionInfomHiA0HHi,?wsdl.neplanservice.NeplanServiceConnectionInfo,?wsdl.neplanservice.LineSectionData,?wsdl.neplanservice.ArrayOfAnalysisReturnInfoCableSizingLineData,?wsdl.neplanservice.ArrayOfAnalysisReturnInfoRelayResultData,?wsdl.neplanservice.AnalysisReturnInfoCableSizingLineData,?wsdl.neplanservice.AnalysisReturnInfoRelayResultData})
        function obj = getInstance(jobj, isArray) 
        % Return a AnalysisParameterSettings object constructed from the Java object jobj.
        % If isArray, jobj is java.util.List of objects and we'll return array.
            if nargin == 0 || isempty(jobj)
                obj = [];
                return
            end
            if nargin > 1 && isArray
                for i = jobj.size : -1 : 1
                    value = wsdl.neplanservice.AnalysisParameterSettings.getInstance(jobj.get(i-1));
                    if ~isempty(value) 
                        obj(i,1) = value;
                    end
                end
                if ~exist('obj','var')
                    obj = [];
                end
            else
                import matlab.wsdl.internal.toMATLAB
                obj = wsdl.neplanservice.AnalysisParameterSettings( ...
                    toMATLAB(jobj.getAnschlKnID,'string',false), ...
                    toMATLAB(jobj.isCalcOnlyLoadedData,'boolean',false), ...
                    toMATLAB(jobj.getConXML,'string',false), ...
                    toMATLAB(jobj.isDoRecondResizing,'boolean',false), ...
                    toMATLAB(jobj.getEleID,'string',false), ...
                    toMATLAB(jobj.isExcludeElementsInMaint,'boolean',false), ...
                    toMATLAB(jobj.isExcludeElementsInstalled,'boolean',false), ...
                    toMATLAB(jobj.isExcludeOutOfOperElements,'boolean',false), ...
                    toMATLAB(jobj.isExcludeProjectedElements,'boolean',false), ...
                    toMATLAB(jobj.getExclutionDateForInstalled,'string',false), ...
                    toMATLAB(jobj.getExclutionDateForOutOfOper,'string',false), ...
                    toMATLAB(jobj.isIncludeBoundaryElementsInCalculation,'boolean',false), ...
                    toMATLAB(jobj.getItemTypeNameForRecondResizingField,'string',false), ...
                    toMATLAB(jobj.getItemlibNameForRecondResizing,'string',false), ...
                    toMATLAB(jobj.getItemlibSubNameForRecondResizing,'string',false), ...
                    toMATLAB(jobj.getLibItemTypeNameForRecondResizing,'string',false), ...
                    toMATLAB(jobj.getLibNameForRecondResizing,'string',false), ...
                    toMATLAB(jobj.getLibSubNameForRecondResizing,'string',false), ...
                    wsdl.neplanservice.ArrayOfguid.getInstance(jobj.getListOfRelayIDs,false), ...
                    wsdl.neplanservice.ArrayOfguid.getInstance(jobj.getListOfSelectedFeederIDs,false), ...
                    wsdl.neplanservice.ArrayOfguid.getInstance(jobj.getListOfSelectedPartNetwIDs,false), ...
                    wsdl.neplanservice.ArrayOfguid.getInstance(jobj.getListOfShortCircuitLocationIDs,false), ...
                    toMATLAB(jobj.getLogName,'string',false), ...
                    toMATLAB(jobj.getMediumType,'string',false), ...
                    toMATLAB(jobj.getNCalc,'int',false), ...
                    toMATLAB(jobj.getRelayID,'string',false), ...
                    wsdl.neplanservice.ArrayOfguid.getInstance(jobj.getSelectedRecondResizElements,false));
            end
        end
    end
end
