classdef AnalysisReturnInfo < matlab.wsdl.internal.WsdlObject
    % AnalysisReturnInfo(AdjustedLoadsFileName,AnalysisID,AnalysisModule,AutomaticSettingsResult,CableSizingLineDataResult,ConXML,DirectoryName,FaultCleared,HasConverged,LoadSummary,LogFilename,NetworkReductionXML,OperationalDataName,RelayData,ResultFile2ButtonName,ResultFile2Name,ResultFilename,ReturnInfo,RunAnalysisWithoutSavingToDB,SelectivityChartResults)  AnalysisReturnInfo object for use with <a href="matlab:doc NeplanService">NeplanService</a> web client
    %
    %     AdjustedLoadsFileName - string
    %     AnalysisID - string
    %     AnalysisModule - string
    %     AutomaticSettingsResult - string
    %     CableSizingLineDataResult - <a href="matlab:doc wsdl.neplanservice.ArrayOfAnalysisReturnInfoCableSizingLineData">ArrayOfAnalysisReturnInfoCableSizingLineData</a>
    %     ConXML - string
    %     DirectoryName - string
    %     FaultCleared - logical or numeric scalar (XML boolean)
    %     HasConverged - logical or numeric scalar (XML boolean)
    %     LoadSummary - string
    %     LogFilename - string
    %     NetworkReductionXML - string
    %     OperationalDataName - string
    %     RelayData - vector of numbers 0-255 (XML base64Binary)
    %     ResultFile2ButtonName - string
    %     ResultFile2Name - string
    %     ResultFilename - string
    %     ReturnInfo - numeric scalar (XML int)
    %     RunAnalysisWithoutSavingToDB - logical or numeric scalar (XML boolean)
    %     SelectivityChartResults - <a href="matlab:doc wsdl.neplanservice.ArrayOfAnalysisReturnInfoRelayResultData">ArrayOfAnalysisReturnInfoRelayResultData</a>
    %
    % 
    %
    % See also <a href="matlab:doc NeplanService">NeplanService</a>.
    
    % This file generated by matlab.wsdl.createWSDLClient at 07-Jan-2018 16:39:55
    % from https://demo.neplan.ch/NEPLAN360_Demo/Services/External/NeplanService.svc?singleWsdl.  
    % Please do not alter this file.
    properties 
        AdjustedLoadsFileName
        AnalysisID
        AnalysisModule
        AutomaticSettingsResult
        CableSizingLineDataResult
        ConXML
        DirectoryName
        FaultCleared
        HasConverged
        LoadSummary
        LogFilename
        NetworkReductionXML
        OperationalDataName
        RelayData
        ResultFile2ButtonName
        ResultFile2Name
        ResultFilename
        ReturnInfo
        RunAnalysisWithoutSavingToDB
        SelectivityChartResults
    end
    
    methods
        function obj = AnalysisReturnInfo(AdjustedLoadsFileName,AnalysisID,AnalysisModule,AutomaticSettingsResult,CableSizingLineDataResult,ConXML,DirectoryName,FaultCleared,HasConverged,LoadSummary,LogFilename,NetworkReductionXML,OperationalDataName,RelayData,ResultFile2ButtonName,ResultFile2Name,ResultFilename,ReturnInfo,RunAnalysisWithoutSavingToDB,SelectivityChartResults)
            if nargin == 0, return, end
            if nargin > 0
                obj.AdjustedLoadsFileName = AdjustedLoadsFileName;
            end
            if nargin > 1
                obj.AnalysisID = AnalysisID;
            end
            if nargin > 2
                obj.AnalysisModule = AnalysisModule;
            end
            if nargin > 3
                obj.AutomaticSettingsResult = AutomaticSettingsResult;
            end
            if nargin > 4
                obj.CableSizingLineDataResult = CableSizingLineDataResult;
            end
            if nargin > 5
                obj.ConXML = ConXML;
            end
            if nargin > 6
                obj.DirectoryName = DirectoryName;
            end
            if nargin > 7
                obj.FaultCleared = FaultCleared;
            end
            if nargin > 8
                obj.HasConverged = HasConverged;
            end
            if nargin > 9
                obj.LoadSummary = LoadSummary;
            end
            if nargin > 10
                obj.LogFilename = LogFilename;
            end
            if nargin > 11
                obj.NetworkReductionXML = NetworkReductionXML;
            end
            if nargin > 12
                obj.OperationalDataName = OperationalDataName;
            end
            if nargin > 13
                obj.RelayData = RelayData;
            end
            if nargin > 14
                obj.ResultFile2ButtonName = ResultFile2ButtonName;
            end
            if nargin > 15
                obj.ResultFile2Name = ResultFile2Name;
            end
            if nargin > 16
                obj.ResultFilename = ResultFilename;
            end
            if nargin > 17
                obj.ReturnInfo = ReturnInfo;
            end
            if nargin > 18
                obj.RunAnalysisWithoutSavingToDB = RunAnalysisWithoutSavingToDB;
            end
            if nargin > 19
                obj.SelectivityChartResults = SelectivityChartResults;
            end
        end
        function obj = set.AdjustedLoadsFileName(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','AdjustedLoadsFileName'},value,'string',true,false);
            obj.AdjustedLoadsFileName = value;
        end        

        function obj = set.AnalysisID(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','AnalysisID'},value,'string',true,false);
            obj.AnalysisID = value;
        end        

        function obj = set.AnalysisModule(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','AnalysisModule'},value,'string',true,false);
            obj.AnalysisModule = value;
        end        

        function obj = set.AutomaticSettingsResult(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','AutomaticSettingsResult'},value,'string',true,false);
            obj.AutomaticSettingsResult = value;
        end        

        function obj = set.CableSizingLineDataResult(obj, value)
            if ~isempty(value) && ~isa(value,'wsdl.neplanservice.ArrayOfAnalysisReturnInfoCableSizingLineData')
                error(message('MATLAB:webservices:VarShouldBeAType','CableSizingLineDataResult', 'wsdl.neplanservice.ArrayOfAnalysisReturnInfoCableSizingLineData', 'ArrayOfAnalysisReturnInfoCableSizingLineData'))
            end
            obj.CableSizingLineDataResult = value;
        end        

        function obj = set.ConXML(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','ConXML'},value,'string',true,false);
            obj.ConXML = value;
        end        

        function obj = set.DirectoryName(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','DirectoryName'},value,'string',true,false);
            obj.DirectoryName = value;
        end        

        function obj = set.FaultCleared(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','FaultCleared'},value,'boolean',true,false);
            obj.FaultCleared = value;
        end        

        function obj = set.HasConverged(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','HasConverged'},value,'boolean',true,false);
            obj.HasConverged = value;
        end        

        function obj = set.LoadSummary(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','LoadSummary'},value,'string',true,false);
            obj.LoadSummary = value;
        end        

        function obj = set.LogFilename(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','LogFilename'},value,'string',true,false);
            obj.LogFilename = value;
        end        

        function obj = set.NetworkReductionXML(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','NetworkReductionXML'},value,'string',true,false);
            obj.NetworkReductionXML = value;
        end        

        function obj = set.OperationalDataName(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','OperationalDataName'},value,'string',true,false);
            obj.OperationalDataName = value;
        end        

        function obj = set.RelayData(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','RelayData'},value,'base64Binary',true,false);
            obj.RelayData = value;
        end        

        function obj = set.ResultFile2ButtonName(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','ResultFile2ButtonName'},value,'string',true,false);
            obj.ResultFile2ButtonName = value;
        end        

        function obj = set.ResultFile2Name(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','ResultFile2Name'},value,'string',true,false);
            obj.ResultFile2Name = value;
        end        

        function obj = set.ResultFilename(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','ResultFilename'},value,'string',true,false);
            obj.ResultFilename = value;
        end        

        function obj = set.ReturnInfo(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','ReturnInfo'},value,'int',true,false);
            obj.ReturnInfo = value;
        end        

        function obj = set.RunAnalysisWithoutSavingToDB(obj, value)
            matlab.wsdl.internal.fromMATLAB({'AnalysisReturnInfo','RunAnalysisWithoutSavingToDB'},value,'boolean',true,false);
            obj.RunAnalysisWithoutSavingToDB = value;
        end        

        function obj = set.SelectivityChartResults(obj, value)
            if ~isempty(value) && ~isa(value,'wsdl.neplanservice.ArrayOfAnalysisReturnInfoRelayResultData')
                error(message('MATLAB:webservices:VarShouldBeAType','SelectivityChartResults', 'wsdl.neplanservice.ArrayOfAnalysisReturnInfoRelayResultData', 'ArrayOfAnalysisReturnInfoRelayResultData'))
            end
            obj.SelectivityChartResults = value;
        end
    end

    methods (Hidden, Access = {?matlab.wsdl.internal.WsdlObject,?NeplanService,?matlab.wsdl.internal.WsdlObject,?wsdl.neplanservice.ExternalProject,?wsdl.neplanservice.ArrayOfdouble,?wsdl.neplanservice.LoadData,?wsdl.neplanservice.string,?wsdl.neplanservice.ArrayOfImportElementItem,?wsdl.neplanservice.ArrayOfLoadData,?wsdl.neplanservice.ArrayOfstring,?wsdl.neplanservice.ArrayOfNeplanServiceElementResult,?wsdl.neplanservice.AnalysisParameterSettings,?wsdl.neplanservice.AnalysisReturnInfo,?wsdl.neplanservice.ArrayOfImportFeederItem,?wsdl.neplanservice.base64Binary,?wsdl.neplanservice.ArrayOfKeyValuePairOfstringstring,?wsdl.neplanservice.ArrayOfKeyValuePairOfstringNeplanServiceConnectionInfomHiA0HHi,?wsdl.neplanservice.ArrayOfNeplanServiceLoadGenerationInfo,?wsdl.neplanservice.ArrayOfguid,?wsdl.neplanservice.NeplanDomainServiceImportReturnInfo,?wsdl.neplanservice.ImportElementItem,?wsdl.neplanservice.ArrayOfTechDataValue,?wsdl.neplanservice.WaterLoadData,?wsdl.neplanservice.ArrayOfLineSectionData,?wsdl.neplanservice.TechDataValue,?wsdl.neplanservice.ImportFeederItem,?wsdl.neplanservice.NeplanServiceElementResult,?wsdl.neplanservice.NeplanServiceLoadGenerationInfo,?wsdl.neplanservice.KeyValuePairOfstringstring,?wsdl.neplanservice.KeyValuePairOfstringNeplanServiceConnectionInfomHiA0HHi,?wsdl.neplanservice.NeplanServiceConnectionInfo,?wsdl.neplanservice.LineSectionData,?wsdl.neplanservice.ArrayOfAnalysisReturnInfoCableSizingLineData,?wsdl.neplanservice.ArrayOfAnalysisReturnInfoRelayResultData,?wsdl.neplanservice.AnalysisReturnInfoCableSizingLineData,?wsdl.neplanservice.AnalysisReturnInfoRelayResultData})
        function validate(obj)
        % Test for required fields
            arrayfun(@(x) x.checkFields({},{},{x.CableSizingLineDataResult,x.SelectivityChartResults}), obj);
        end
    end

    methods (Hidden, Access = protected)
        function jobj = getOneObj(obj)
        % Return the Java object corresponding to this object.  Intended
        % to be invoked from superclass.
            obj.validate
            import matlab.wsdl.internal.fromMATLAB
            jobj = neplanservice.AnalysisReturnInfo;  % create empty Java object
            % populate fields of object
            jobj.setAdjustedLoadsFileName(fromMATLAB({'AnalysisReturnInfo','AdjustedLoadsFileName'},obj.AdjustedLoadsFileName,'string',true));
            jobj.setAnalysisID(fromMATLAB({'AnalysisReturnInfo','AnalysisID'},obj.AnalysisID,'string',true));
            jobj.setAnalysisModule(fromMATLAB({'AnalysisReturnInfo','AnalysisModule'},obj.AnalysisModule,'string',true));
            jobj.setAutomaticSettingsResult(fromMATLAB({'AnalysisReturnInfo','AutomaticSettingsResult'},obj.AutomaticSettingsResult,'string',true));
            if ~isempty(obj.CableSizingLineDataResult)
                jobj.setCableSizingLineDataResult(obj.CableSizingLineDataResult.getObj);
            end
            jobj.setConXML(fromMATLAB({'AnalysisReturnInfo','ConXML'},obj.ConXML,'string',true));
            jobj.setDirectoryName(fromMATLAB({'AnalysisReturnInfo','DirectoryName'},obj.DirectoryName,'string',true));
            jobj.setFaultCleared(fromMATLAB({'AnalysisReturnInfo','FaultCleared'},obj.FaultCleared,'boolean',true));
            jobj.setHasConverged(fromMATLAB({'AnalysisReturnInfo','HasConverged'},obj.HasConverged,'boolean',true));
            jobj.setLoadSummary(fromMATLAB({'AnalysisReturnInfo','LoadSummary'},obj.LoadSummary,'string',true));
            jobj.setLogFilename(fromMATLAB({'AnalysisReturnInfo','LogFilename'},obj.LogFilename,'string',true));
            jobj.setNetworkReductionXML(fromMATLAB({'AnalysisReturnInfo','NetworkReductionXML'},obj.NetworkReductionXML,'string',true));
            jobj.setOperationalDataName(fromMATLAB({'AnalysisReturnInfo','OperationalDataName'},obj.OperationalDataName,'string',true));
            jobj.setRelayData(fromMATLAB({'AnalysisReturnInfo','RelayData'},obj.RelayData,'base64Binary',true));
            jobj.setResultFile2ButtonName(fromMATLAB({'AnalysisReturnInfo','ResultFile2ButtonName'},obj.ResultFile2ButtonName,'string',true));
            jobj.setResultFile2Name(fromMATLAB({'AnalysisReturnInfo','ResultFile2Name'},obj.ResultFile2Name,'string',true));
            jobj.setResultFilename(fromMATLAB({'AnalysisReturnInfo','ResultFilename'},obj.ResultFilename,'string',true));
            jobj.setReturnInfo(fromMATLAB({'AnalysisReturnInfo','ReturnInfo'},obj.ReturnInfo,'int',true));
            jobj.setRunAnalysisWithoutSavingToDB(fromMATLAB({'AnalysisReturnInfo','RunAnalysisWithoutSavingToDB'},obj.RunAnalysisWithoutSavingToDB,'boolean',true));
            if ~isempty(obj.SelectivityChartResults)
                jobj.setSelectivityChartResults(obj.SelectivityChartResults.getObj);
            end
        end
    end

    methods (Static, Hidden, Access = {?NeplanService,?matlab.wsdl.internal.WsdlObject,?wsdl.neplanservice.ExternalProject,?wsdl.neplanservice.ArrayOfdouble,?wsdl.neplanservice.LoadData,?wsdl.neplanservice.string,?wsdl.neplanservice.ArrayOfImportElementItem,?wsdl.neplanservice.ArrayOfLoadData,?wsdl.neplanservice.ArrayOfstring,?wsdl.neplanservice.ArrayOfNeplanServiceElementResult,?wsdl.neplanservice.AnalysisParameterSettings,?wsdl.neplanservice.AnalysisReturnInfo,?wsdl.neplanservice.ArrayOfImportFeederItem,?wsdl.neplanservice.base64Binary,?wsdl.neplanservice.ArrayOfKeyValuePairOfstringstring,?wsdl.neplanservice.ArrayOfKeyValuePairOfstringNeplanServiceConnectionInfomHiA0HHi,?wsdl.neplanservice.ArrayOfNeplanServiceLoadGenerationInfo,?wsdl.neplanservice.ArrayOfguid,?wsdl.neplanservice.NeplanDomainServiceImportReturnInfo,?wsdl.neplanservice.ImportElementItem,?wsdl.neplanservice.ArrayOfTechDataValue,?wsdl.neplanservice.WaterLoadData,?wsdl.neplanservice.ArrayOfLineSectionData,?wsdl.neplanservice.TechDataValue,?wsdl.neplanservice.ImportFeederItem,?wsdl.neplanservice.NeplanServiceElementResult,?wsdl.neplanservice.NeplanServiceLoadGenerationInfo,?wsdl.neplanservice.KeyValuePairOfstringstring,?wsdl.neplanservice.KeyValuePairOfstringNeplanServiceConnectionInfomHiA0HHi,?wsdl.neplanservice.NeplanServiceConnectionInfo,?wsdl.neplanservice.LineSectionData,?wsdl.neplanservice.ArrayOfAnalysisReturnInfoCableSizingLineData,?wsdl.neplanservice.ArrayOfAnalysisReturnInfoRelayResultData,?wsdl.neplanservice.AnalysisReturnInfoCableSizingLineData,?wsdl.neplanservice.AnalysisReturnInfoRelayResultData})
        function obj = getInstance(jobj, isArray) 
        % Return a AnalysisReturnInfo object constructed from the Java object jobj.
        % If isArray, jobj is java.util.List of objects and we'll return array.
            if nargin == 0 || isempty(jobj)
                obj = [];
                return
            end
            if nargin > 1 && isArray
                for i = jobj.size : -1 : 1
                    value = wsdl.neplanservice.AnalysisReturnInfo.getInstance(jobj.get(i-1));
                    if ~isempty(value) 
                        obj(i,1) = value;
                    end
                end
                if ~exist('obj','var')
                    obj = [];
                end
            else
                import matlab.wsdl.internal.toMATLAB
                obj = wsdl.neplanservice.AnalysisReturnInfo( ...
                    toMATLAB(jobj.getAdjustedLoadsFileName,'string',false), ...
                    toMATLAB(jobj.getAnalysisID,'string',false), ...
                    toMATLAB(jobj.getAnalysisModule,'string',false), ...
                    toMATLAB(jobj.getAutomaticSettingsResult,'string',false), ...
                    wsdl.neplanservice.ArrayOfAnalysisReturnInfoCableSizingLineData.getInstance(jobj.getCableSizingLineDataResult,false), ...
                    toMATLAB(jobj.getConXML,'string',false), ...
                    toMATLAB(jobj.getDirectoryName,'string',false), ...
                    toMATLAB(jobj.isFaultCleared,'boolean',false), ...
                    toMATLAB(jobj.isHasConverged,'boolean',false), ...
                    toMATLAB(jobj.getLoadSummary,'string',false), ...
                    toMATLAB(jobj.getLogFilename,'string',false), ...
                    toMATLAB(jobj.getNetworkReductionXML,'string',false), ...
                    toMATLAB(jobj.getOperationalDataName,'string',false), ...
                    toMATLAB(jobj.getRelayData,'base64Binary',false), ...
                    toMATLAB(jobj.getResultFile2ButtonName,'string',false), ...
                    toMATLAB(jobj.getResultFile2Name,'string',false), ...
                    toMATLAB(jobj.getResultFilename,'string',false), ...
                    toMATLAB(jobj.getReturnInfo,'int',false), ...
                    toMATLAB(jobj.isRunAnalysisWithoutSavingToDB,'boolean',false), ...
                    wsdl.neplanservice.ArrayOfAnalysisReturnInfoRelayResultData.getInstance(jobj.getSelectivityChartResults,false));
            end
        end
    end
end
