#ifndef __NEPMODULEDEF_H__
#define __NEPMODULEDEF_H__


#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#define BCP_SELECTED_MODULE_NONE				0x0000
#define BCP_SELECTED_MODULE_LF					0x0001
#define BCP_SELECTED_MODULE_LF_WITH_PROFILE			0x0002
#define BCP_SELECTED_MODULE_OPTIMAL_SEPERATION_POINTS			0x0003
#define BCP_SELECTED_MODULE_OPTIMAL_DISTRIBUTION_NETWORK			0x0004
#define BCP_SELECTED_MODULE_CONTINGENCY_ANALYSIS			0x0005
#define BCP_SELECTED_MODULE_OPTIMAL_POWER_FLOW			0x0006

#define BCP_SELECTED_MODULE_SC					0x0007
#define BCP_SELECTED_MODULE_HS					0x0008
#define BCP_SELECTED_MODULE_MS					0x0009
#define BCP_SELECTED_MODULE_VS					0x000A
#define BCP_SELECTED_MODULE_SS					0x000B
#define BCP_SELECTED_MODULE_TS					0x000C
#define BCP_SELECTED_MODULE_RELIABILITY	0x000D
#define BCP_SELECTED_MODULE_CP					0x000E
#define BCP_SELECTED_MODULE_GW					0x0101
#define BCP_SELECTED_MODULE_INVA				0x000F
#define BCP_SELECTED_MODULE_SIMP				0x0010
#define BCP_SELECTED_MODULE_FF            0x0011
#define BCP_SELECTED_MODULE_SIMP_LA       0x0012
#define BCP_SELECTED_MODULE_CABLEDIM       0x0013
#define BCP_SELECTED_MODULE_ATC					0x0014
#define BCP_SELECTED_MODULE_FEEDERREINF    0x0015
#define BCP_SELECTED_MODULE_RESUPPLY      0x00F0
#define BCP_SELECTED_MODULE_SEL           0x00F1
#define BCP_SELECTED_MODULE_DIST           0x00F2
#define BCP_SELECTED_MODULE_NSCALC         0x00F3
#define BCP_SELECTED_MODULE_DYNAMIC         0x00F4
#endif // !defined(__NEPMODULEDEF_H__)
